#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/arlow/modular_arlow.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_arlow.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
from dataclasses import dataclass
from typing import Optional, Union

import torch
import torch.nn.functional as F
from torch import nn
from torch.nn import LayerNorm

from ...activations import ACT2FN
from ...cache_utils import Cache, DynamicCache
from ...generation import GenerationMixin
from ...integrations import use_kernel_forward_from_hub
from ...masking_utils import create_causal_mask, create_sliding_window_causal_mask
from ...modeling_layers import (
    GenericForQuestionAnswering,
    GenericForSequenceClassification,
    GenericForTokenClassification,
    GradientCheckpointingLayer,
)
from ...modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast, ModelOutput
from ...modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring, can_return_tuple, logging
from .configuration_arlow import ArlowConfig, ArlowVisionConfig


logger = logging.get_logger(__name__)


@dataclass
@auto_docstring(
    custom_intro="""
    Base class for Arlow multimodal model outputs, with hidden states and M-ROPE deltas.
    """
)
class ArlowMultimodalModelOutputWithPast(ModelOutput):
    r"""
    past_key_values (`Cache`, *optional*, returned when `use_cache=True` is passed or when `config.use_cache=True`):
        Contains pre-computed hidden-states (key and values in the self-attention blocks) that can be used to speed up sequential decoding.
    rope_deltas (`torch.LongTensor` of shape `(batch_size, )`, *optional*):
        The rope index difference between sequence length and multimodal rope for M-ROPE.
    """

    last_hidden_state: Optional[torch.FloatTensor] = None
    past_key_values: Optional[Cache] = None
    hidden_states: Optional[tuple[torch.FloatTensor]] = None
    attentions: Optional[tuple[torch.FloatTensor]] = None
    rope_deltas: Optional[torch.LongTensor] = None


@dataclass
@auto_docstring(
    custom_intro="""
    Base class for Arlow multimodal causal language model outputs.
    """
)
class ArlowMultimodalCausalLMOutputWithPast(ModelOutput):
    r"""
    loss (`torch.FloatTensor` of shape `(1,)`, *optional*, returned when `labels` is provided):
        Language modeling loss (for next-token prediction).
    logits (`torch.FloatTensor` of shape `(batch_size, sequence_length, config.vocab_size)`):
        Prediction scores of the language modeling head (scores for each vocabulary token before SoftMax).
    past_key_values (`Cache`, *optional*, returned when `use_cache=True` is passed or when `config.use_cache=True`):
        Contains pre-computed hidden-states (key and values in the self-attention blocks) that can be used to speed up sequential decoding.
    rope_deltas (`torch.LongTensor` of shape `(batch_size, )`, *optional*):
        The rope index difference between sequence length and multimodal rope for M-ROPE.
    """

    loss: Optional[torch.FloatTensor] = None
    logits: Optional[torch.FloatTensor] = None
    past_key_values: Optional[Cache] = None
    hidden_states: Optional[tuple[torch.FloatTensor]] = None
    attentions: Optional[tuple[torch.FloatTensor]] = None
    rope_deltas: Optional[torch.LongTensor] = None


@use_kernel_forward_from_hub("RMSNorm")
class ArlowRMSNorm(nn.Module):
    def __init__(self, hidden_size: int, eps: float = 1e-6):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class ArlowRotaryEmbedding(nn.Module):
    def __init__(self, config: ArlowConfig, device=None):
        super().__init__()
        rope_config = getattr(config, "rope_parameters", None)
        if rope_config is not None and not isinstance(rope_config, dict):
            raise ValueError("rope_parameters must be a dict if provided")
        if isinstance(rope_config, dict):
            self.rope_type = rope_config.get("rope_type", rope_config.get("type"))
            if self.rope_type is None:
                logger.warning("rope_parameters provided without 'rope_type'/'type'; defaulting to 'default'.")
                self.rope_type = "default"
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config

        # Handle default rope type
        rope_init_fn = self.compute_default_rope_parameters
        if self.rope_type != "default":
            rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = rope_init_fn(self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = inv_freq

    @staticmethod
    def compute_default_rope_parameters(
        config: Optional[ArlowConfig] = None,
        device: Optional["torch.device"] = None,
        seq_len: Optional[int] = None,
        **rope_kwargs,
    ) -> tuple["torch.Tensor", float]:
        """
        Computes the inverse frequencies for default RoPE (no scaling).
        """
        if config is not None:
            # Access rope_theta from rope_parameters if available, otherwise fallback to config attribute
            if hasattr(config, "rope_parameters") and config.rope_parameters:
                base = config.rope_parameters.get("rope_theta", config.rope_theta)
            else:
                base = config.rope_theta
            head_dim = config.head_dim
            if head_dim is None:
                head_dim = config.hidden_size // config.num_attention_heads
        else:
            base = rope_kwargs.get("base", 10000.0)
            head_dim = rope_kwargs.get("dim")

        inv_freq = 1.0 / (base ** (torch.arange(0, head_dim, 2, dtype=torch.int64).float().to(device) / head_dim))
        return inv_freq, 1.0

    @torch.no_grad()
    @dynamic_rope_update
    def forward(self, x: torch.Tensor, position_ids: torch.LongTensor):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            # Concatenate for standard RoPE (matches Llama implementation)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


class VisionRotaryEmbedding(nn.Module):
    """Rotary position embeddings for vision transformer."""

    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, dim: int, theta: float = 10000.0) -> None:
        super().__init__()
        inv_freq = 1.0 / (theta ** (torch.arange(0, dim, 2, dtype=torch.float) / dim))
        self.register_buffer("inv_freq", inv_freq, persistent=False)

    def forward(self, seqlen: int) -> torch.Tensor:
        seq = torch.arange(seqlen, device=self.inv_freq.device, dtype=self.inv_freq.dtype)
        freqs = torch.outer(seq, self.inv_freq)
        return freqs


class ArlowMultimodalRotaryEmbedding(nn.Module):
    """
    M-ROPE with interleaved frequency layout for (temporal, height, width) dimensions.
    Follows Qwen3VL's implementation with apply_interleaved_mrope.
    """

    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: ArlowConfig, device=None):
        super().__init__()
        self.config = config
        self.head_dim = config.head_dim
        self.mrope_sections = config.mrope_sections

        # Validate sections
        if sum(self.mrope_sections) != self.head_dim:
            raise ValueError(f"Sum of mrope_sections {self.mrope_sections} must equal head_dim {self.head_dim}")

        # Get rope parameters
        rope_theta = config.rope_theta
        if hasattr(config, "rope_parameters") and config.rope_parameters:
            rope_theta = config.rope_parameters.get("rope_theta", rope_theta)

        # Create single inv_freq for head_dim // 2 (like Qwen3VL)
        inv_freq = 1.0 / (
            rope_theta ** (torch.arange(0, self.head_dim, 2, dtype=torch.float, device=device) / self.head_dim)
        )
        self.register_buffer("inv_freq", inv_freq, persistent=False)

        self.attention_scaling = 1.0

    def apply_interleaved_mrope(self, freqs: torch.Tensor, mrope_section: list[int]) -> torch.Tensor:
        """
        Apply interleaved MRoPE to 3D rotary embeddings.
        Reorganizes frequency layout from chunked [TTT...HHH...WWW] to
        interleaved [THTHWHTHW...TT], preserving frequency continuity.

        Args:
            freqs: (3, batch, seq_len, head_dim // 2)
            mrope_section: (3,) list of section dimensions [t_dim, h_dim, w_dim]

        Returns:
            freqs_t: (batch, seq_len, head_dim // 2) with interleaved frequencies
        """
        freqs_t = freqs[0]  # Start with temporal dimension
        for dim, offset in enumerate((1, 2), start=1):  # H, W
            length = mrope_section[dim] * 3
            idx = slice(offset, length, 3)
            freqs_t[..., idx] = freqs[dim, ..., idx]
        return freqs_t

    @torch.no_grad()
    def forward(self, x: torch.Tensor, position_ids: torch.LongTensor):
        """
        Args:
            x: Input tensor (used for device/dtype)
            position_ids: Shape (3, batch, seq_len) containing [t, h, w] position indices

        Returns:
            Tuple of (cos, sin) with shape (batch, seq_len, head_dim)
        """
        # Expand position_ids if needed (handle 2D case)
        if position_ids.ndim == 2:
            position_ids = position_ids[None, ...].expand(3, position_ids.shape[0], -1)

        # Expand inv_freq to shape (3, batch, head_dim//2, 1)
        inv_freq_expanded = self.inv_freq[None, None, :, None].float().expand(3, position_ids.shape[1], -1, 1)
        # position_ids shape: (3, batch, 1, seq_len)
        position_ids_expanded = position_ids[:, :, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):
            # Compute frequencies: (3, batch, seq_len, head_dim//2)
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(2, 3)
            # Apply interleaved MRoPE
            freqs = self.apply_interleaved_mrope(freqs, self.mrope_sections)
            # Concatenate for standard RoPE application
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


def rotate_half(x: torch.Tensor) -> torch.Tensor:
    # Interleave even/odd features: (-x_odd, x_even)
    x_even = x[..., ::2]
    x_odd = x[..., 1::2]
    return torch.stack((-x_odd, x_even), dim=-1).reshape_as(x)


def apply_rotary_pos_emb(q, k, cos, sin, unsqueeze_dim=1):
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


class ArlowAttention(nn.Module):
    def __init__(self, config: ArlowConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.hidden_size = config.hidden_size
        self.num_heads = config.num_attention_heads
        self.num_kv_heads = config.num_key_value_heads
        self.head_dim = getattr(config, "head_dim", None) or (self.hidden_size // self.num_heads)
        self.num_key_value_groups = self.num_heads // self.num_kv_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        # Sliding window support
        self.sliding_window = config.sliding_window if config.layer_types[layer_idx] == "sliding_attention" else None

        self.q_proj = nn.Linear(
            self.hidden_size,
            self.num_heads * self.head_dim,
            bias=self.config.attention_bias,
        )
        self.k_proj = nn.Linear(
            self.hidden_size,
            self.num_kv_heads * self.head_dim,
            bias=self.config.attention_bias,
        )
        self.v_proj = nn.Linear(
            self.hidden_size,
            self.num_kv_heads * self.head_dim,
            bias=self.config.attention_bias,
        )
        # Always keep output projection bias disabled regardless of attention_bias.
        self.o_proj = nn.Linear(self.num_heads * self.head_dim, self.hidden_size, bias=False)

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_values: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor]]:
        input_shape = hidden_states.shape[:-1]
        q_shape = (*input_shape, self.num_heads, self.head_dim)
        kv_shape = (*input_shape, self.num_kv_heads, self.head_dim)

        query_states = self.q_proj(hidden_states).view(q_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(kv_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(kv_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        if past_key_values is not None:
            cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx, cache_kwargs)

        # For SDPA, during incremental decoding (query_len == 1), we should pass None as the mask
        # to allow SDPA to use is_causal=False, avoiding shape issues with 4D masks
        if (
            getattr(self.config, "_attn_implementation", "eager") == "sdpa"
            and attention_mask is not None
            and query_states.shape[2] == 1  # q_len == 1 (incremental decoding)
        ):
            attention_mask = None

        # Dispatch to proper attention implementation
        attention_interface = eager_attention_forward
        if getattr(self.config, "_attn_implementation", "eager") != "eager":
            attention_interface = ALL_ATTENTION_FUNCTIONS[self.config._attn_implementation]

        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=self.attention_dropout if self.training else 0.0,
            scaling=self.scaling,
            sliding_window=self.sliding_window,
            **kwargs,
        )

        # Fold heads to last dim before output projection
        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class ArlowMLP(nn.Module):
    def __init__(self, config: ArlowConfig):
        super().__init__()
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]
        self.dropout = nn.Dropout(config.mlp_dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return self.dropout(x)


class ArlowDecoderLayer(nn.Module):
    def __init__(self, config: ArlowConfig, layer_idx: int):
        super().__init__()
        self.attention_type = config.layer_types[layer_idx]
        self.self_attn = ArlowAttention(config=config, layer_idx=layer_idx)
        self.mlp = ArlowMLP(config)
        self.input_layernorm = ArlowRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = ArlowRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.resid_dropout = nn.Dropout(config.resid_dropout)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor]]:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)
        attn_out, attn_weights = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_embeddings=position_embeddings,
            past_key_values=past_key_values,
            cache_position=cache_position,
            **kwargs,
        )
        hidden_states = residual + self.resid_dropout(attn_out)

        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        mlp_out = self.mlp(hidden_states)
        hidden_states = residual + self.resid_dropout(mlp_out)

        output_attentions = kwargs.get("output_attentions", False)
        if output_attentions:
            return (hidden_states, attn_weights)

        return (hidden_states,)


class PatchEmbed(nn.Module):
    """Convert images/videos to patch embeddings."""

    def __init__(
        self,
        patch_size: int = 14,
        temporal_patch_size: int = 2,
        in_channels: int = 3,
        embed_dim: int = 1280,
    ):
        super().__init__()
        self.patch_size = patch_size
        self.temporal_patch_size = temporal_patch_size
        self.in_channels = in_channels
        self.embed_dim = embed_dim

        # 3D convolution for video, 2D for images
        kernel_size = (temporal_patch_size, patch_size, patch_size)
        self.proj = nn.Conv3d(in_channels, embed_dim, kernel_size=kernel_size, stride=kernel_size, bias=False)

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        """
        Args:
            hidden_states: (batch * num_tiles, channels, temporal, height, width)
        Returns:
            embeddings: (batch * num_tiles, embed_dim, T, H, W) -> flattened to (total_tokens, embed_dim)
        """
        print(f"[DEBUG VISION] PatchEmbed.forward input shape: {hidden_states.shape}")
        hidden_states = self.proj(hidden_states)
        print(f"[DEBUG VISION] PatchEmbed.forward after projection: {hidden_states.shape}")
        # Flatten spatial dimensions: (B, C, T, H, W) -> (B, T*H*W, C)
        batch_size = hidden_states.shape[0]
        hidden_states = hidden_states.reshape(batch_size, self.embed_dim, -1).transpose(1, 2)
        print(f"[DEBUG VISION] PatchEmbed.forward output shape: {hidden_states.shape}")
        return hidden_states


class PatchMerger(nn.Module):
    """Merge vision patches and project to text model dimension."""

    def __init__(self, dim: int, context_dim: int, spatial_merge_size: int = 2):
        super().__init__()
        self.hidden_size = context_dim * (spatial_merge_size**2)
        self.ln_q = LayerNorm(context_dim, eps=1e-6)
        self.mlp = nn.Sequential(
            nn.Linear(self.hidden_size, self.hidden_size),
            nn.GELU(),
            nn.Linear(self.hidden_size, dim),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: vision embeddings of shape (total_patches, embed_dim)
        Returns:
            merged: (total_merged_patches, hidden_size)
        """
        print(f"[DEBUG VISION] PatchMerger.forward input shape: {x.shape}")
        x = self.ln_q(x)
        # Reshape for spatial merging (simplified version - actual impl may vary)
        # For now, apply MLP directly
        output = self.mlp(x)
        print(f"[DEBUG VISION] PatchMerger.forward output shape: {output.shape}")
        return output


def apply_rotary_pos_emb_vision(
    q: torch.Tensor, k: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor
) -> tuple[torch.Tensor, torch.Tensor]:
    """Apply RoPE to vision transformer Q/K tensors."""
    orig_q_dtype = q.dtype
    orig_k_dtype = k.dtype
    q, k = q.float(), k.float()
    cos, sin = cos.unsqueeze(-2).float(), sin.unsqueeze(-2).float()
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    q_embed = q_embed.to(orig_q_dtype)
    k_embed = k_embed.to(orig_k_dtype)
    return q_embed, k_embed


class ArlowVisionAttention(nn.Module):
    """Vision self-attention with RoPE."""

    def __init__(self, config: ArlowVisionConfig):
        super().__init__()
        self.embed_dim = config.embed_dim
        self.num_heads = config.num_heads
        self.head_dim = self.embed_dim // self.num_heads
        self.scaling = self.head_dim**-0.5

        self.qkv = nn.Linear(self.embed_dim, self.embed_dim * 3, bias=True)
        self.proj = nn.Linear(self.embed_dim, self.embed_dim, bias=True)

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,
    ) -> torch.Tensor:
        """
        Args:
            hidden_states: (total_tokens, embed_dim)
            position_embeddings: (cos, sin) for RoPE
        """
        print(f"[DEBUG VISION] ArlowVisionAttention.forward input shape: {hidden_states.shape}")
        batch_size, seq_length = (
            hidden_states.shape[0],
            hidden_states.shape[1] if hidden_states.dim() > 2 else hidden_states.shape[0],
        )

        # Compute Q, K, V
        qkv = self.qkv(hidden_states).reshape(-1, 3, self.num_heads, self.head_dim)
        query_states, key_states, value_states = qkv.unbind(1)
        print(f"[DEBUG VISION] ArlowVisionAttention.forward Q/K/V shapes: {query_states.shape}")

        # Apply RoPE if provided
        if position_embeddings is not None:
            cos, sin = position_embeddings
            query_states, key_states = apply_rotary_pos_emb_vision(query_states, key_states, cos, sin)
            print(f"[DEBUG VISION] ArlowVisionAttention.forward after RoPE: {query_states.shape}")

        # Reshape for attention: (seq, heads, head_dim) -> (1, seq, heads, head_dim) -> (1, heads, seq, head_dim)
        query_states = query_states.unsqueeze(0).transpose(1, 2)
        key_states = key_states.unsqueeze(0).transpose(1, 2)
        value_states = value_states.unsqueeze(0).transpose(1, 2)

        # Scaled dot-product attention
        attn_weights = torch.matmul(query_states, key_states.transpose(-2, -1)) * self.scaling
        attn_weights = F.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
        attn_output = torch.matmul(attn_weights, value_states)

        # Reshape back
        attn_output = attn_output.transpose(1, 2).reshape(-1, self.embed_dim)
        attn_output = self.proj(attn_output)
        print(f"[DEBUG VISION] ArlowVisionAttention.forward output shape: {attn_output.shape}")

        return attn_output


class ArlowVisionBlock(GradientCheckpointingLayer):
    """Vision transformer block with attention and MLP."""

    def __init__(self, config: ArlowVisionConfig):
        super().__init__()
        self.norm1 = LayerNorm(config.embed_dim, eps=1e-6)
        self.norm2 = LayerNorm(config.embed_dim, eps=1e-6)
        self.attn = ArlowVisionAttention(config)
        mlp_hidden_dim = int(config.embed_dim * config.mlp_ratio)
        # Inline MLP instead of separate class
        self.fc1 = nn.Linear(config.embed_dim, mlp_hidden_dim)
        self.act = ACT2FN[config.hidden_act]
        self.fc2 = nn.Linear(mlp_hidden_dim, config.embed_dim)

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,
        **kwargs,
    ) -> torch.Tensor:
        # Self-attention with residual
        hidden_states = hidden_states + self.attn(
            self.norm1(hidden_states),
            position_embeddings=position_embeddings,
        )
        # MLP with residual (inline)
        residual = hidden_states
        hidden_states = self.norm2(hidden_states)
        hidden_states = self.fc2(self.act(self.fc1(hidden_states)))
        hidden_states = residual + hidden_states
        return hidden_states


class ArlowPreTrainedModel(PreTrainedModel):
    config_class = ArlowConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["ArlowDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values", "rotary_emb.inv_freq"]
    is_loaded_in_8bit = False
    is_loaded_in_4bit = False
    _supports_flash_attn = True
    _supports_sdpa = True
    _can_record_outputs = {}

    def _init_weights(self, module: nn.Module):
        std = self.config.initializer_range
        if isinstance(module, nn.Linear):
            nn.init.normal_(module.weight, mean=0.0, std=std)
            if module.bias is not None:
                nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            nn.init.normal_(module.weight, mean=0.0, std=std)
            if module.padding_idx is not None:
                nn.init.zeros_(module.weight[module.padding_idx])
        elif isinstance(module, ArlowRMSNorm):
            nn.init.ones_(module.weight)


@auto_docstring
class ArlowVisionTransformerPretrainedModel(ArlowPreTrainedModel):
    """Vision encoder for Arlow multimodal models."""

    config_class = ArlowVisionConfig
    input_modalities = ["image", "video"]
    _no_split_modules = ["ArlowVisionBlock"]

    def __init__(self, config: ArlowVisionConfig):
        super().__init__(config)
        self.config = config
        self.spatial_merge_size = config.spatial_merge_size

        # Patch embedding
        self.patch_embed = PatchEmbed(
            patch_size=config.patch_size,
            temporal_patch_size=config.temporal_patch_size,
            in_channels=config.in_channels,
            embed_dim=config.embed_dim,
        )

        # Rotary position embeddings for vision
        head_dim = config.embed_dim // config.num_heads
        self.rotary_pos_emb = VisionRotaryEmbedding(head_dim // 2)

        # Transformer blocks
        self.blocks = nn.ModuleList([ArlowVisionBlock(config) for _ in range(config.depth)])

        # Patch merger to project to text dimension
        self.merger = PatchMerger(
            dim=config.hidden_size,
            context_dim=config.embed_dim,
            spatial_merge_size=config.spatial_merge_size,
        )

        self.gradient_checkpointing = False

        self.post_init()

    def get_dtype(self) -> torch.dtype:
        return self.blocks[0].fc2.weight.dtype

    def get_device(self) -> torch.device:
        return self.blocks[0].fc2.weight.device

    def forward(
        self,
        pixel_values: torch.Tensor,
        grid_thw: Optional[torch.LongTensor] = None,
    ) -> torch.Tensor:
        """
        Args:
            pixel_values: (batch, channels, temporal, height, width)
            grid_thw: (num_images/videos, 3) containing [temporal, height, width] dimensions
        Returns:
            vision_embeddings: (total_tokens, hidden_size)
        """
        print(f"[DEBUG VISION] ArlowVisionTransformer.forward pixel_values shape: {pixel_values.shape}")
        if grid_thw is not None:
            print(f"[DEBUG VISION] ArlowVisionTransformer.forward grid_thw shape: {grid_thw.shape}")

        # Patch embedding
        hidden_states = self.patch_embed(pixel_values)  # (batch, num_patches, embed_dim)

        # Get RoPE embeddings
        # Simplified - in practice you'd compute based on grid_thw
        seq_len = hidden_states.shape[1]
        print(f"[DEBUG VISION] ArlowVisionTransformer.forward seq_len for RoPE: {seq_len}")
        rotary_pos_emb = self.rotary_pos_emb(seq_len)
        # Convert to cos/sin
        cos = rotary_pos_emb.cos()
        sin = rotary_pos_emb.sin()
        position_embeddings = (cos, sin)

        # Apply transformer blocks
        for idx, block in enumerate(self.blocks):
            if self.gradient_checkpointing and self.training:
                hidden_states = block._gradient_checkpointing_func(
                    block.__call__,
                    hidden_states,
                    position_embeddings,
                )
            else:
                hidden_states = block(hidden_states, position_embeddings)
            print(f"[DEBUG VISION] ArlowVisionTransformer block {idx} output shape: {hidden_states.shape}")

        # Merge patches and project to text dimension
        hidden_states = hidden_states.reshape(-1, self.config.embed_dim)
        print(f"[DEBUG VISION] ArlowVisionTransformer before merger: {hidden_states.shape}")
        vision_embeddings = self.merger(hidden_states)
        print(f"[DEBUG VISION] ArlowVisionTransformer final output: {vision_embeddings.shape}")

        return vision_embeddings


@auto_docstring
class ArlowTextModel(ArlowPreTrainedModel):
    """Text-only decoder model for Arlow (used internally by ArlowModel)."""

    config_class = ArlowConfig
    input_modalities = "text"

    def __init__(self, config: ArlowConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size
        self.has_sliding_layers = "sliding_attention" in config.layer_types

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [ArlowDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = ArlowRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = ArlowRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        self.post_init()

    # emb getters
    def get_input_embeddings(self):
        return self.embed_tokens

    def set_input_embeddings(self, value):
        self.embed_tokens = value

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        cache_position: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        # Handle input_ids vs inputs_embeds
        if input_ids is None and inputs_embeds is None:
            raise ValueError("You must specify either input_ids or inputs_embeds")

        # When both are provided, prefer inputs_embeds (this is expected during generation)
        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        # Recompute cache_position if it doesn't match the input length
        if cache_position is not None and cache_position.shape[0] != inputs_embeds.shape[1]:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens,
                past_seen_tokens + inputs_embeds.shape[1],
                device=inputs_embeds.device,
            )
        elif cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens,
                past_seen_tokens + inputs_embeds.shape[1],
                device=inputs_embeds.device,
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        # It may already have been prepared by e.g. `generate`
        if not isinstance(causal_mask_mapping := attention_mask, dict):
            # Prepare mask arguments
            mask_kwargs = {
                "config": self.config,
                "input_embeds": inputs_embeds,
                "attention_mask": attention_mask,
                "cache_position": cache_position,
                "past_key_values": past_key_values,
                "position_ids": position_ids,
            }
            # Create the masks
            causal_mask_mapping = {
                "full_attention": create_causal_mask(**mask_kwargs),
            }
            # The sliding window alternating layers are not always activated depending on the config
            if self.has_sliding_layers:
                causal_mask_mapping["sliding_attention"] = create_sliding_window_causal_mask(**mask_kwargs)

        hidden_states = inputs_embeds
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        # Collect hidden states and attentions for output if requested
        output_hidden_states = kwargs.get("output_hidden_states", self.config.output_hidden_states)
        output_attentions = kwargs.get("output_attentions", self.config.output_attentions)
        all_hidden_states = () if output_hidden_states else None
        all_self_attns = () if output_attentions else None

        # Ensure output flags are in kwargs for decoder layers
        kwargs["output_hidden_states"] = output_hidden_states
        kwargs["output_attentions"] = output_attentions

        # Gradient checkpointing support
        if self.gradient_checkpointing and self.training:
            if use_cache:
                logger.warning_once(
                    "`use_cache=True` is incompatible with gradient checkpointing. Setting use_cache=False."
                )
            use_cache = False

        if all_hidden_states is not None:
            all_hidden_states += (hidden_states,)

        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            layer_outputs = decoder_layer(
                hidden_states,
                attention_mask=causal_mask_mapping[decoder_layer.attention_type],
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **kwargs,
            )

            hidden_states = layer_outputs[0] if isinstance(layer_outputs, tuple) else layer_outputs

            if all_self_attns is not None and isinstance(layer_outputs, tuple) and len(layer_outputs) > 1:
                all_self_attns += (layer_outputs[1],)

            if all_hidden_states is not None:
                all_hidden_states += (hidden_states,)

        hidden_states = self.norm(hidden_states)
        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
            hidden_states=all_hidden_states,
            attentions=all_self_attns,
        )


@auto_docstring
class ArlowForCausalLM(ArlowPreTrainedModel, GenerationMixin):
    """Text-only causal language model (no vision)."""

    _tied_weights_keys = ["lm_head.weight"]

    def __init__(self, config: ArlowConfig):
        super().__init__(config)
        self.model = ArlowTextModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)

        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> CausalLMOutputWithPast:
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            # Align labels to sliced logits window before shifting
            labels_window = labels[:, slice_indices]
            shift_logits = logits[..., :-1, :].contiguous()
            shift_labels = labels_window[..., 1:].contiguous()
            ignore_index = self.config.pad_token_id if self.config.pad_token_id is not None else -100
            loss = F.cross_entropy(
                shift_logits.view(-1, self.config.vocab_size),
                shift_labels.view(-1),
                ignore_index=ignore_index,
            )

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )

    def prepare_inputs_for_generation(
        self,
        input_ids: torch.LongTensor,
        past_key_values: Optional[Cache] = None,
        attention_mask: Optional[torch.Tensor] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs,
    ):
        # Only use inputs_embeds for the first forward pass (when cache is empty)
        # After that, we use input_ids for subsequent generation steps
        # Check if cache has tokens, not just if cache object exists
        cache_length = past_key_values.get_seq_length() if past_key_values is not None else 0

        if cache_length > 0:
            # We have cached tokens, so we're in a subsequent generation step
            # Special case: if input_ids is empty but inputs_embeds is provided,
            # we need to slice inputs_embeds to only the new tokens not in cache
            if input_ids is not None and input_ids.shape[1] == 0 and inputs_embeds is not None:
                # Slice inputs_embeds to only process tokens not yet in cache
                if inputs_embeds.shape[1] > cache_length:
                    inputs_embeds = inputs_embeds[:, cache_length:]
                    input_ids = None
            else:
                # For assisted/speculative decoding, we may need to process multiple new tokens
                # Use cache_position to determine how many tokens to keep
                if cache_position is not None and len(cache_position) > 1:
                    # Assisted generation: keep multiple tokens
                    input_ids = input_ids[:, cache_position[0] :]
                else:
                    # Normal generation: just the last token
                    input_ids = input_ids[:, -1:]
                inputs_embeds = None
        elif inputs_embeds is not None:
            # First step with inputs_embeds (cache is empty or doesn't exist) - don't pass input_ids
            input_ids = None

        return {
            "input_ids": input_ids,
            "past_key_values": past_key_values,
            "attention_mask": attention_mask,
            "inputs_embeds": inputs_embeds,
            "cache_position": cache_position,
            **kwargs,
        }

    # reorder cache (beam)
    def _reorder_cache(self, past_key_values, beam_idx):
        if past_key_values is not None and hasattr(past_key_values, "reorder_cache"):
            past_key_values.reorder_cache(beam_idx)
        return past_key_values


@auto_docstring
class ArlowModel(ArlowPreTrainedModel):
    """
    Main multimodal model combining vision encoder and text decoder.
    This is the primary model class that handles both image/video and text inputs.
    Follows Qwen2VL architecture pattern.
    """

    base_model_prefix = ""
    _checkpoint_conversion_mapping = {"^model": "language_model"}
    accepts_loss_kwargs = False

    def __init__(self, config: ArlowConfig):
        super().__init__(config)

        # Vision encoder
        self.visual = ArlowVisionTransformerPretrainedModel._from_config(config.vision_config)

        # Text model (language decoder)
        self.language_model = ArlowTextModel._from_config(config)

        # Multimodal RoPE for combined vision-text sequences
        self.multimodal_rotary_emb = ArlowMultimodalRotaryEmbedding(config)

        # Cache for rope deltas
        self.rope_deltas = None

        self.post_init()

    def get_input_embeddings(self):
        return self.language_model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.language_model.set_input_embeddings(value)

    def set_decoder(self, decoder):
        self.language_model = decoder

    def get_decoder(self):
        return self.language_model

    def get_image_features(
        self,
        pixel_values: torch.FloatTensor,
        image_grid_thw: Optional[torch.LongTensor] = None,
    ) -> torch.FloatTensor:
        """Extract image features from vision encoder."""
        print(f"[DEBUG VISION] get_image_features: pixel_values shape={pixel_values.shape}")
        if image_grid_thw is not None:
            print(f"[DEBUG VISION] get_image_features: image_grid_thw shape={image_grid_thw.shape}")

        # Get dtype from vision model, fallback to float32
        target_dtype = self.visual.get_dtype() if hasattr(self.visual, "get_dtype") else torch.float32
        pixel_values = pixel_values.to(dtype=target_dtype)

        image_embeds = self.visual(pixel_values, image_grid_thw)
        print(f"[DEBUG VISION] get_image_features: raw image_embeds shape={image_embeds.shape}")

        split_sizes = (image_grid_thw.prod(-1) // self.config.vision_config.spatial_merge_size**2).tolist()
        print(f"[DEBUG VISION] get_image_features: split_sizes={split_sizes}")
        image_embeds = torch.split(image_embeds, split_sizes)
        print(f"[DEBUG VISION] get_image_features: num splits={len(image_embeds)}")
        return image_embeds

    def get_video_features(
        self,
        pixel_values_videos: torch.FloatTensor,
        video_grid_thw: Optional[torch.LongTensor] = None,
    ) -> torch.FloatTensor:
        """Extract video features from vision encoder (same as images with temporal dim)."""
        print(f"[DEBUG VIDEO] get_video_features: pixel_values_videos shape={pixel_values_videos.shape}")
        if video_grid_thw is not None:
            print(f"[DEBUG VIDEO] get_video_features: video_grid_thw shape={video_grid_thw.shape}")

        # Get dtype from vision model, fallback to float32
        target_dtype = self.visual.get_dtype() if hasattr(self.visual, "get_dtype") else torch.float32
        pixel_values_videos = pixel_values_videos.to(dtype=target_dtype)

        video_embeds = self.visual(pixel_values_videos, video_grid_thw)
        print(f"[DEBUG VIDEO] get_video_features: raw video_embeds shape={video_embeds.shape}")

        split_sizes = (video_grid_thw.prod(-1) // self.config.vision_config.spatial_merge_size**2).tolist()
        print(f"[DEBUG VIDEO] get_video_features: split_sizes={split_sizes}")
        video_embeds = torch.split(video_embeds, split_sizes)
        print(f"[DEBUG VIDEO] get_video_features: num splits={len(video_embeds)}")
        return video_embeds

    def get_placeholder_mask(
        self,
        input_ids: torch.LongTensor,
        inputs_embeds: torch.FloatTensor,
        image_features: Optional[torch.FloatTensor] = None,
        video_features: Optional[torch.FloatTensor] = None,
    ):
        """
        Obtains multimodal placeholder mask from `input_ids` or `inputs_embeds`, and checks that
        the placeholder token count is equal to the length of multimodal features.
        """
        if input_ids is None:
            special_image_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.image_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_image_mask = special_image_mask.all(-1)
            special_video_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.video_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_video_mask = special_video_mask.all(-1)
        else:
            special_image_mask = input_ids == self.config.image_token_id
            special_video_mask = input_ids == self.config.video_token_id

        n_image_tokens = special_image_mask.sum()
        special_image_mask = special_image_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if image_features is not None and inputs_embeds[special_image_mask].numel() != image_features.numel():
            raise ValueError(
                f"Image features and image tokens do not match: tokens: {n_image_tokens}, features {image_features.shape[0]}"
            )

        n_video_tokens = special_video_mask.sum()
        special_video_mask = special_video_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if video_features is not None and inputs_embeds[special_video_mask].numel() != video_features.numel():
            raise ValueError(
                f"Videos features and video tokens do not match: tokens: {n_video_tokens}, features {video_features.shape[0]}"
            )

        return special_image_mask, special_video_mask

    def get_rope_index(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        image_grid_thw: Optional[torch.LongTensor] = None,
        video_grid_thw: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Calculate the 3D rope index based on image and video's temporal, height and width in LLM.

        Explanation:
            Each embedding sequence contains vision embedding and text embedding or just contains text embedding.

            For pure text embedding sequence, the rotary position embedding has no difference with modern LLMs.
            Examples:
                input_ids: [T T T T T], here T is for text.
                temporal position_ids: [0, 1, 2, 3, 4]
                height position_ids: [0, 1, 2, 3, 4]
                width position_ids: [0, 1, 2, 3, 4]

            For vision and text embedding sequence, we calculate 3D rotary position embedding for vision part
            and 1D rotary position embedding for text part.
            Examples:
                Assume we have a video input with 3 temporal patches, 2 height patches and 2 width patches.
                input_ids: [V V V V V V V V V V V V T T T T T], here V is for vision.
                vision temporal position_ids: [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]
                vision height position_ids: [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1]
                vision width position_ids: [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
                text temporal position_ids: [3, 4, 5, 6, 7]
                text height position_ids: [3, 4, 5, 6, 7]
                text width position_ids: [3, 4, 5, 6, 7]
                Here we calculate the text start position_ids as the max vision position_ids plus 1.

        Args:
            input_ids (`torch.LongTensor` of shape `(batch_size, sequence_length)`):
                Indices of input sequence tokens in the vocabulary.
            image_grid_thw (`torch.LongTensor` of shape `(num_images, 3)`, *optional*):
                The temporal, height and width of feature shape of each image in LLM.
            video_grid_thw (`torch.LongTensor` of shape `(num_videos, 3)`, *optional*):
                The temporal, height and width of feature shape of each video in LLM.
            attention_mask (`torch.Tensor` of shape `(batch_size, sequence_length)`, *optional*):
                Mask to avoid performing attention on padding token indices.

        Returns:
            position_ids (`torch.LongTensor` of shape `(3, batch_size, sequence_length)`)
            mrope_position_deltas (`torch.Tensor` of shape `(batch_size)`)
        """
        spatial_merge_size = self.config.vision_config.spatial_merge_size
        image_token_id = self.config.image_token_id
        video_token_id = self.config.video_token_id
        vision_start_token_id = self.config.vision_start_token_id
        mrope_position_deltas = []

        if input_ids is not None and (image_grid_thw is not None or video_grid_thw is not None):
            total_input_ids = input_ids
            if attention_mask is None:
                attention_mask = torch.ones_like(total_input_ids)
            position_ids = torch.ones(
                3, input_ids.shape[0], input_ids.shape[1], dtype=input_ids.dtype, device=input_ids.device
            )
            image_index, video_index = 0, 0
            for i, input_ids in enumerate(total_input_ids):
                input_ids = input_ids[attention_mask[i].to(input_ids.device) == 1]
                image_nums, video_nums = 0, 0
                vision_start_indices = torch.argwhere(input_ids == vision_start_token_id).squeeze(1)
                vision_tokens = input_ids[vision_start_indices + 1]
                image_nums = (vision_tokens == image_token_id).sum()
                video_nums = (vision_tokens == video_token_id).sum()
                input_tokens = input_ids.tolist()
                llm_pos_ids_list: list = []
                st = 0
                remain_images, remain_videos = image_nums, video_nums
                for _ in range(image_nums + video_nums):
                    if image_token_id in input_tokens and remain_images > 0:
                        ed_image = input_tokens.index(image_token_id, st)
                    else:
                        ed_image = len(input_tokens) + 1
                    if video_token_id in input_tokens and remain_videos > 0:
                        ed_video = input_tokens.index(video_token_id, st)
                    else:
                        ed_video = len(input_tokens) + 1
                    if ed_image < ed_video:
                        t, h, w = (
                            image_grid_thw[image_index][0],
                            image_grid_thw[image_index][1],
                            image_grid_thw[image_index][2],
                        )
                        image_index += 1
                        remain_images -= 1
                        ed = ed_image
                    else:
                        t, h, w = (
                            video_grid_thw[video_index][0],
                            video_grid_thw[video_index][1],
                            video_grid_thw[video_index][2],
                        )
                        video_index += 1
                        remain_videos -= 1
                        ed = ed_video
                    llm_grid_t, llm_grid_h, llm_grid_w = (
                        t.item(),
                        h.item() // spatial_merge_size,
                        w.item() // spatial_merge_size,
                    )
                    text_len = ed - st

                    st_idx = llm_pos_ids_list[-1].max() + 1 if len(llm_pos_ids_list) > 0 else 0
                    llm_pos_ids_list.append(torch.arange(text_len).view(1, -1).expand(3, -1) + st_idx)

                    t_index = torch.arange(llm_grid_t).view(-1, 1).expand(-1, llm_grid_h * llm_grid_w).flatten()
                    h_index = torch.arange(llm_grid_h).view(1, -1, 1).expand(llm_grid_t, -1, llm_grid_w).flatten()
                    w_index = torch.arange(llm_grid_w).view(1, 1, -1).expand(llm_grid_t, llm_grid_h, -1).flatten()
                    llm_pos_ids_list.append(torch.stack([t_index, h_index, w_index]) + text_len + st_idx)
                    st = ed + llm_grid_t * llm_grid_h * llm_grid_w

                if st < len(input_tokens):
                    st_idx = llm_pos_ids_list[-1].max() + 1 if len(llm_pos_ids_list) > 0 else 0
                    text_len = len(input_tokens) - st
                    llm_pos_ids_list.append(torch.arange(text_len).view(1, -1).expand(3, -1) + st_idx)

                llm_positions = torch.cat(llm_pos_ids_list, dim=1).reshape(3, -1)
                position_ids[..., i, attention_mask[i] == 1] = llm_positions.to(position_ids.device)
                mrope_position_deltas.append(llm_positions.max() + 1 - len(total_input_ids[i]))
            mrope_position_deltas = torch.tensor(mrope_position_deltas, device=input_ids.device).unsqueeze(1)
            return position_ids, mrope_position_deltas
        else:
            if attention_mask is not None:
                position_ids = attention_mask.long().cumsum(-1) - 1
                position_ids.masked_fill_(attention_mask == 0, 1)
                position_ids = position_ids.unsqueeze(0).expand(3, -1, -1).to(attention_mask.device)
                max_position_ids = position_ids.max(0, keepdim=False)[0].max(-1, keepdim=True)[0]
                mrope_position_deltas = max_position_ids + 1 - attention_mask.shape[-1]
            else:
                position_ids = (
                    torch.arange(input_ids.shape[1], device=input_ids.device)
                    .view(1, 1, -1)
                    .expand(3, input_ids.shape[0], -1)
                )
                mrope_position_deltas = torch.zeros(
                    [input_ids.shape[0], 1],
                    device=input_ids.device,
                    dtype=input_ids.dtype,
                )

            return position_ids, mrope_position_deltas

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        pixel_values: Optional[torch.Tensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        image_grid_thw: Optional[torch.LongTensor] = None,
        video_grid_thw: Optional[torch.LongTensor] = None,
        rope_deltas: Optional[torch.LongTensor] = None,
        cache_position: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> ArlowMultimodalModelOutputWithPast:
        """
        Forward pass combining vision and text modalities.

        Args:
            input_ids: Text token IDs with image/video placeholder tokens
            pixel_values: Image tensor (batch, channels, height, width)
            pixel_values_videos: Video tensor (batch, channels, frames, height, width)
            image_grid_thw: Image grid dimensions (num_images, 3) as [temporal=1, height, width]
            video_grid_thw: Video grid dimensions (num_videos, 3) as [temporal, height, width]
            rope_deltas: Rope index difference for M-ROPE
        """
        # Get text embeddings
        if inputs_embeds is None:
            inputs_embeds = self.get_input_embeddings()(input_ids)
            print(f"[DEBUG MULTIMODAL] ArlowModel.forward: text embeddings shape={inputs_embeds.shape}")

        # Process vision inputs if provided using masked_scatter
        if pixel_values is not None:
            print("[DEBUG MULTIMODAL] ArlowModel.forward: processing image inputs")
            image_embeds = self.get_image_features(pixel_values, image_grid_thw)
            image_embeds = torch.cat(image_embeds, dim=0).to(inputs_embeds.device, inputs_embeds.dtype)
            print(f"[DEBUG MULTIMODAL] ArlowModel.forward: concatenated image_embeds shape={image_embeds.shape}")
            image_mask, _ = self.get_placeholder_mask(
                input_ids, inputs_embeds=inputs_embeds, image_features=image_embeds
            )
            print(
                f"[DEBUG MULTIMODAL] ArlowModel.forward: image_mask shape={image_mask.shape}, sum={image_mask.sum()}"
            )
            inputs_embeds = inputs_embeds.masked_scatter(image_mask, image_embeds)
            print(
                f"[DEBUG MULTIMODAL] ArlowModel.forward: after image scatter, inputs_embeds shape={inputs_embeds.shape}"
            )

        if pixel_values_videos is not None:
            print("[DEBUG MULTIMODAL] ArlowModel.forward: processing video inputs")
            video_embeds = self.get_video_features(pixel_values_videos, video_grid_thw)
            video_embeds = torch.cat(video_embeds, dim=0).to(inputs_embeds.device, inputs_embeds.dtype)
            print(f"[DEBUG MULTIMODAL] ArlowModel.forward: concatenated video_embeds shape={video_embeds.shape}")
            _, video_mask = self.get_placeholder_mask(
                input_ids, inputs_embeds=inputs_embeds, video_features=video_embeds
            )
            print(
                f"[DEBUG MULTIMODAL] ArlowModel.forward: video_mask shape={video_mask.shape}, sum={video_mask.sum()}"
            )
            inputs_embeds = inputs_embeds.masked_scatter(video_mask, video_embeds)
            print(
                f"[DEBUG MULTIMODAL] ArlowModel.forward: after video scatter, inputs_embeds shape={inputs_embeds.shape}"
            )

        # Compute position_ids with M-ROPE if needed
        if position_ids is None:
            if (
                not hasattr(self, "rope_deltas")
                or self.rope_deltas is None
                or cache_position is None
                or cache_position[0] == 0
            ):
                position_ids, rope_deltas = self.get_rope_index(
                    input_ids, image_grid_thw, video_grid_thw, attention_mask
                )
                self.rope_deltas = rope_deltas
            # Use cached rope_deltas for subsequent steps
            else:
                batch_size, seq_length, _ = inputs_embeds.shape
                position_ids = torch.arange(seq_length, device=inputs_embeds.device)
                position_ids = position_ids.view(1, 1, -1).expand(3, batch_size, -1)
                if cache_position is not None:
                    delta = (cache_position[0] + self.rope_deltas).to(inputs_embeds.device)
                else:
                    delta = torch.zeros((batch_size, seq_length), device=inputs_embeds.device)
                delta = delta.repeat_interleave(batch_size // delta.shape[0], dim=0)
                position_ids = position_ids + delta.to(position_ids.device)

        # Forward through text model (language decoder) with M-ROPE
        # Use multimodal rotary embedding for position embeddings
        position_embeddings = self.multimodal_rotary_emb(inputs_embeds, position_ids)

        outputs = self.language_model(
            input_ids=None,  # We're using inputs_embeds instead
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            cache_position=cache_position,
            use_cache=use_cache,
            position_embeddings=position_embeddings,
            **kwargs,
        )

        return ArlowMultimodalModelOutputWithPast(
            last_hidden_state=outputs.last_hidden_state,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            rope_deltas=self.rope_deltas,
        )


@auto_docstring
class ArlowForConditionalGeneration(ArlowPreTrainedModel, GenerationMixin):
    """
    Arlow model for conditional generation (multimodal: text + images/videos).
    This is the main model for VLM tasks. Uses ArlowModel internally.
    """

    _tied_weights_keys = ["lm_head.weight"]

    def __init__(self, config: ArlowConfig):
        super().__init__(config)
        self.model = ArlowModel(config)  # Now uses the multimodal ArlowModel
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)

        self.post_init()

    def get_input_embeddings(self):
        return self.model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.model.set_input_embeddings(value)

    def get_image_features(self, pixel_values: torch.FloatTensor, image_grid_thw: Optional[torch.LongTensor] = None):
        return self.model.get_image_features(pixel_values, image_grid_thw)

    def get_video_features(
        self, pixel_values_videos: torch.FloatTensor, video_grid_thw: Optional[torch.LongTensor] = None
    ):
        return self.model.get_video_features(pixel_values_videos, video_grid_thw)

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        pixel_values: Optional[torch.Tensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        image_grid_thw: Optional[torch.LongTensor] = None,
        video_grid_thw: Optional[torch.LongTensor] = None,
        rope_deltas: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> ArlowMultimodalCausalLMOutputWithPast:
        """
        Forward pass for multimodal conditional generation.

        Args:
            image_grid_thw (`torch.LongTensor`, *optional*):
                Image grid dimensions of shape `(num_images, 3)` as `[temporal=1, height, width]`.
            video_grid_thw (`torch.LongTensor`, *optional*):
                Video grid dimensions of shape `(num_videos, 3)` as `[temporal, height, width]`.

        Example:
        ```python
        >>> from transformers import AutoProcessor, ArlowForConditionalGeneration
        >>> model = ArlowForConditionalGeneration.from_pretrained("yuchenxie/arlow-vlm")
        >>> processor = AutoProcessor.from_pretrained("yuchenxie/arlow-vlm")
        >>>
        >>> messages = [{
        ...     "role": "user",
        ...     "content": [
        ...         {"type": "image", "image": "path/to/image.jpg"},
        ...         {"type": "text", "text": "Describe this image."},
        ...     ],
        ... }]
        >>>
        >>> inputs = processor(text=messages, images=..., return_tensors="pt")
        >>> outputs = model.generate(**inputs, max_new_tokens=100)
        >>> processor.batch_decode(outputs, skip_special_tokens=True)[0]
        ```
        """
        outputs: ArlowMultimodalModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            pixel_values=pixel_values,
            pixel_values_videos=pixel_values_videos,
            image_grid_thw=image_grid_thw,
            video_grid_thw=video_grid_thw,
            rope_deltas=rope_deltas,
            use_cache=use_cache,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            labels_window = labels[:, slice_indices]
            shift_logits = logits[..., :-1, :].contiguous()
            shift_labels = labels_window[..., 1:].contiguous()
            ignore_index = self.config.pad_token_id if self.config.pad_token_id is not None else -100
            loss = F.cross_entropy(
                shift_logits.view(-1, self.config.vocab_size),
                shift_labels.view(-1),
                ignore_index=ignore_index,
            )

        return ArlowMultimodalCausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            rope_deltas=outputs.rope_deltas,
        )

    def prepare_inputs_for_generation(
        self,
        input_ids: torch.LongTensor,
        past_key_values: Optional[Cache] = None,
        attention_mask: Optional[torch.Tensor] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        pixel_values: Optional[torch.Tensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        image_grid_thw: Optional[torch.LongTensor] = None,
        video_grid_thw: Optional[torch.LongTensor] = None,
        rope_deltas: Optional[torch.LongTensor] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs,
    ):
        """Prepare inputs for generation, handling both text-only and multimodal inputs."""
        cache_length = past_key_values.get_seq_length() if past_key_values is not None else 0

        # Only process vision on first forward pass
        if cache_length > 0:
            pixel_values = None
            pixel_values_videos = None
            image_grid_thw = None
            video_grid_thw = None

            if input_ids is not None and input_ids.shape[1] == 0 and inputs_embeds is not None:
                if inputs_embeds.shape[1] > cache_length:
                    inputs_embeds = inputs_embeds[:, cache_length:]
                    input_ids = None
            else:
                if cache_position is not None and len(cache_position) > 1:
                    input_ids = input_ids[:, cache_position[0] :]
                else:
                    input_ids = input_ids[:, -1:]
                inputs_embeds = None
        elif inputs_embeds is not None:
            input_ids = None

        return {
            "input_ids": input_ids,
            "past_key_values": past_key_values,
            "attention_mask": attention_mask,
            "inputs_embeds": inputs_embeds,
            "pixel_values": pixel_values,
            "pixel_values_videos": pixel_values_videos,
            "image_grid_thw": image_grid_thw,
            "video_grid_thw": video_grid_thw,
            "rope_deltas": rope_deltas,
            "cache_position": cache_position,
            **kwargs,
        }

    def _reorder_cache(self, past_key_values, beam_idx):
        if past_key_values is not None and hasattr(past_key_values, "reorder_cache"):
            past_key_values.reorder_cache(beam_idx)
        return past_key_values


class ArlowForSequenceClassification(GenericForSequenceClassification, ArlowPreTrainedModel): ...


class ArlowForQuestionAnswering(GenericForQuestionAnswering, ArlowPreTrainedModel): ...


class ArlowForTokenClassification(GenericForTokenClassification, ArlowPreTrainedModel): ...


__all__ = [
    "ArlowPreTrainedModel",
    "ArlowTextModel",
    "ArlowModel",
    "ArlowForCausalLM",
    "ArlowForConditionalGeneration",
    "ArlowVisionTransformerPretrainedModel",
    "ArlowForSequenceClassification",
    "ArlowForQuestionAnswering",
    "ArlowForTokenClassification",
]
