name: Build PR Documentation

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@main
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: transformers
      languages: en
      # Temporary pin to work around datasets exception in the docbuilder. Remove after docker images and main have
      # the right dependencies (which **should** be the case by 2025-07-20). See
      # https://github.com/huggingface/transformers/actions/runs/16365952006/job/46243081358?pr=38545
      pre_command: uv pip install datasets>=2.15.0
